
["Attack Damage"]

	["Attack Damage"."Misc Weapons/Tools"]
		"Damage of the Fairy Sword" = 10
		"Damage of the Big Hammer" = 15
		"Damage of the Rat Sword" = 10
		"Damage of the Nightmare Sword" = 30
		"Damage of the Experience Sword" = 10
		"Damage of the Poison Sword" = 10
		"Damage of the Prismatic Reaper" = 29
		"Damage of the Mantis Claw" = 10

	["Attack Damage"."Kyanite Weapons/Tools"]
		"Damage of the Kyanite Shovel" = 4
		"Damage of the Kyanite Axe" = 9
		"Damage of the Kyanite Hoe" = 1
		"Damage of the Kyanite Sword" = 6
		"Damage of the Kyanite Pickaxe" = 4

	["Attack Damage"."Crystal Wood Weapons/Tools"]
		"Damage of the Crystal Wood Shovel" = 3
		"Damage of the Crystal Wood Sword" = 5
		"Damage of the Crystal Wood Pickaxe" = 3
		"Damage of the Crystal Wood Axe" = 9
		"Damage of the Crystal Wood Hoe" = 1

	["Attack Damage"."Silver Weapons/Tools"]
		"Damage of the Silver Sword" = 6
		"Damage of the Silver Shovel" = 5
		"Damage of the Silver Axe" = 9
		"Damage of the Silver Hoe" = 1
		"Damage of the Silver Pickaxe" = 4

	["Attack Damage"."Tin Weapons/Tools"]
		"Damage of the Tin Sword" = 6
		"Damage of the Tin Pickaxe" = 4
		"Damage of the Tin Shovel" = 4
		"Damage of the Tin Axe" = 9
		"Damage of the Tin Hoe" = 1

	["Attack Damage"."Cat's Eye Weapons/Tools"]
		"Damage of the Cat's Eye Shovel" = 11
		"Damage of the Cat's Eye Pickaxe" = 10
		"Damage of the Cat's Eye Sword" = 12
		"Damage of the Cat's Eye Axe" = 14
		"Damage of the Cat's Eye Hoe" = 1

	["Attack Damage"."Emerald Weapons/Tools"]
		"Damage of the Emerald Sword" = 10
		"Damage of the Emerald Pickaxe" = 8
		"Damage of the Emerald Shovel" = 9
		"Damage of the Emerald Axe" = 12
		"Damage of the Emerald Hoe" = 1

	["Attack Damage"."Big Weapons/Tools"]
		"Damage of the Queen Scale Battle Axe" = 666
		"Damage of the Attitude Adjuster" = 65
		"Damage of the Battle Axe" = 50
		"Damage of the Slayer Chainsaw" = 40
		"Damage of the Big Bertha" = 500
		"Damage of the Royal Guardian Sword" = 750

	["Attack Damage"."Platinum Weapons/Tools"]
		"Damage of the Platinum Pickaxe" = 8
		"Damage of the Platinum Axe" = 12
		"Damage of the Platinum Shovel" = 9
		"Damage of the Platinum Hoe" = 1
		"Damage of the Platinum Sword" = 10

	["Attack Damage"."Tiger's Eye Weapons/Tools"]
		"Damage of the Tiger's Eye Pickaxe" = 10
		"Damage of the Tiger's Eye Shovel" = 11
		"Damage of the Tiger's Eye Sword" = 12
		"Damage of the Tiger's Eye Axe" = 14
		"Damage of the Tiger's Eye Hoe" = 1

	["Attack Damage"."Amethyst Weapons/Tools"]
		"Damage of the Amethyst Shovel" = 14
		"Damage of the Amethyst Hoe" = 1
		"Damage of the Amethyst Sword" = 15
		"Damage of the Amethyst Axe" = 17
		"Damage of the Amethyst Pickaxe" = 13

	["Attack Damage"."Ruby Weapons/Tools"]
		"Damage of the Ruby Sword" = 20
		"Damage of the Ruby Shovel" = 19
		"Damage of the Ruby Axe" = 22
		"Damage of the Ruby Pickaxe" = 18
		"Damage of the Ruby Hoe" = 1

	["Attack Damage"."Pink Tourmaline Weapons/Tools"]
		"Damage of the Pink Tourmaline Axe" = 13
		"Damage of the Pink Tourmaline Shovel" = 10
		"Damage of the Pink Tourmaline Hoe" = 1
		"Damage of the Pink Tourmaline Pickaxe" = 9
		"Damage of the Pink Tourmaline Sword" = 11

	["Attack Damage"."Copper Weapons/Tools"]
		"Damage of the Copper Pickaxe" = 3
		"Damage of the Copper Axe" = 9
		"Damage of the Copper Hoe" = 1
		"Damage of the Copper Shovel" = 4
		"Damage of the Copper Sword" = 5

	["Attack Damage"."Ultimate Weapons/Tools"]
		"Damage of the Ultimate Axe" = 42
		"Damage of the Ultimate Hoe" = 1
		"Damage of the Ultimate Pickaxe" = 38
		"Damage Multiplier of the Ultimate Bow's Power Enchantment" = 0.5
		"Damage of the Ultimate Sword" = 40
		"Damage of the Ultimate Shovel" = 39
		#How much damage the Ultimate bow will add up to the base arrow damage
		"Additional Damage of the Ultimate Bow Arrows" = 5.0

[Functionality]

	[Functionality."Tools/Weapons"]
		#If disabled, auto-enchanted items will be able to be enchanted manually.
		"Auto-enchant specific tools and weapons" = true

		[Functionality."Tools/Weapons".Explosions]

			[Functionality."Tools/Weapons".Explosions."Ray Gun"]
				#0 = NONE - The Ray Gun will not affect the terrain.
				#1 = BREAK - The Ray Gun will drop some blocks that it breaks.
				#2 = DESTROY - The Ray Gun will destroy blocks and never drop them.
				#Range: 0 ~ 2
				"Ray Gun explosion type" = 2
				"Fire from Ray Gun explosion" = false
				"Ray Gun explosion size" = 6

			[Functionality."Tools/Weapons".Explosions."Attitude Adjuster"]
				#0 = NONE - The Attitude Adjuster will not affect the terrain.
				#1 = BREAK - The Attitude Adjuster will drop some blocks that it breaks.
				#2 = DESTROY - The Attitude Adjuster will destroy blocks and never drop them.
				#Range: 0 ~ 2
				"Attitude Adjuster explosion type" = 2
				"Fire from Attitude Adjuster explosion" = false
				"Attitude Adjuster explosion size" = 4

			[Functionality."Tools/Weapons".Explosions."Thunder Staff"]
				#0 = NONE - The Thunder Staff will not affect the terrain.
				#1 = BREAK - The Thunder Staff will drop some blocks that it breaks. (May not work due to lightning)
				#2 = DESTROY - The Thunder Staff will destroy blocks and never drop them.
				#Range: 0 ~ 2
				"Thunder Staff explosion type" = 2
				"Fire from Thunder Staff explosion" = true
				"Thunder Staff explosion size" = 4

	[Functionality.Breeding]
		#Will Enchanted Animals be Breedable?
		"Enchanted Animal Breeding" = false

	[Functionality."Update Checker"]
		#Send messages when there is a new update?
		"Show Update Messages" = false

	[Functionality.Spawners]
		#0 = No Blocking - All Spawn Eggs can be used on a Spawner in Survival.
		#1 = Block All Spawn Eggs - All Spawn Eggs will be blocked from being used on a Spawner in Survival.
		#2 = Only Block Chaos Awakens - Only Spawn Eggs from Chaos Awakens will be blocked from being used on a Spawner in Survival.
		#Range: 0 ~ 2
		"Spawn Eggs on Spawners in Survival?" = 1

	[Functionality."Ender Dragon"]
		#Will the Ender Dragon Egg respawn after the first death?
		"Ender Dragon Egg Respawn" = true
		#Will the Ender Dragon drop her head?
		"Ender Dragon Head Drop" = true

	[Functionality.Textures]
		#Will holiday special textures be obtainable?
		"Obtainable Holiday Textures" = true

["Log messages"]
	"Terraforged check message active" = false

["World Generation"]
	"Enable fossilised spawn egg generation" = true
	"Enable ore generation" = true
	"Enable limestone generation in the mining dimension" = true
	"Enable infested ore generation" = true
	#Will DZ ores spawn in the Overworld?
	"Overworld DZ Ores" = false
	"Enable marble generation in the mining dimension" = true
	#Will Nests spawn in the Overworld or the Ant Dimensions?
	"Ant Nest generation" = true
	"Enable DZ ore generation" = true

	["World Generation"."Specific Ore Spawning"]
		"Titanium ore generation" = true
		"Uranium ore generation" = true
		"Sunstone ore generation" = true
		"Bloodstone ore generation" = true
		"Silver ore generation" = true
		"Aluminum ore generation" = true
		"Tin ore generation" = true
		"Ruby ore generation" = true
		"Tiger's Eye ore generation" = true
		"Platinum ore generation" = true
		"Amethyst ore generation" = true
		"Salt ore generation" = true
		"Copper ore generation" = true

	["World Generation".Structures]
		#Will Wasp Nests be generated?
		"Generate Wasp Nests" = true
		#Will Jungle Ent Trees be generated?
		"Generate Jungle Ent Trees" = true
		#Will Acacia Ent Trees be generated?
		"Generate Acacia Ent Trees" = true
		#Will Dark Oak Ent Trees be generated?
		"Generate Dark Oak Ent Trees" = true
		#Will Crimson Ent Trees be generated?
		"Generate Crimson Ent Trees" = true
		#Will Birch Ent Trees be generated?
		"Generate Birch Ent Trees" = true
		#Will Oak Ent Trees be generated?
		"Generate Oak Ent Trees" = true
		#Will Warped Ent Trees be generated?
		"Generate Warped Ent Trees" = true
		#Will Spruce Ent Trees be generated?
		"Generate Spruce Ent Trees" = true

[Dimensions]
	#Will the Butterfly teleport you to its Dimension?
	"Butterfly Teleport" = true
	#Will the Brown Ant teleport you to its Dimension?
	"Brown Ant Teleport" = true
	#Will the Rainbow Ant teleport you to its Dimension?
	"Rainbow Ant Teleport" = true
	#Will the Red Ant teleport you to its Dimension?
	"Red Ant Teleport" = true
	#Will the Unstable Ant teleport you to its Dimension?
	"Unstable Ant Teleport" = true
	#Will the Termite teleport you to its Dimension?
	"Termite Teleport" = true
	#Disable the requirement of needing an empty inventory to enter the Crystal World (Termite Dimension)?
	"Crystal World Requires Empty Inventory" = true

[Entity]

	[Entity."Wandering Trader"]
		#Can the Wandering Trader sell Uranium and Titanium?
		"Uranium and Titanium from Wandering Trader?" = false
		#Can the Wandering Trader sell Triffid Goo?
		"Triffid Goo from Wandering Trader?" = true

		[Entity."Wandering Trader"."Robo Warrior"]
			#0 = NONE - The Robo Warrior will not affect the terrain.
			#1 = BREAK - The Robo Warrior will drop some blocks that it breaks.
			#2 = DESTROY - The Robo Warrior will destroy blocks and never drop them.
			#Range: 0 ~ 2
			"Ray Gun explosion type" = 2
			"Fire from Robo Warrior explosion" = false
			"Robo Warrior explosion size" = 6

