
["Log messages"]
	"Terraforged check message active" = true

[Functionality]

	[Functionality."Tools/Weapons"]
		#If disabled, auto-enchanted items will have to be enchanted manually.
		"Auto-enchant specific tools and weapons" = true

		[Functionality."Tools/Weapons".Swords]

			[Functionality."Tools/Weapons".Swords."Experience Sword"]
				"Enable Experience Sword Weapon Bonus" = true
				#Range: 0 ~ 1000
				"Multiplier for XP dropped by killing mobs" = 2

		[Functionality."Tools/Weapons".Explosions]

			[Functionality."Tools/Weapons".Explosions."Ray Gun"]
				#NONE - The Ray Gun will not affect the terrain.
				#BREAK - The Ray Gun will drop some blocks that it breaks.
				#DESTROY - The Ray Gun will destroy blocks and never drop them.
				#Allowed Values: NONE, BREAK, DESTROY
				"Ray Gun explosion type" = "BREAK"
				"Fire from Ray Gun explosion" = false
				#Range: 0 ~ 500
				"Ray Gun explosion size" = 6

			[Functionality."Tools/Weapons".Explosions."Attitude Adjuster"]
				#NONE - The Attitude Adjuster will not affect the terrain.
				#BREAK - The Attitude Adjuster will drop some blocks that it breaks.
				#DESTROY - The Attitude Adjuster will destroy blocks and never drop them.
				#Allowed Values: NONE, BREAK, DESTROY
				"Attitude Adjuster explosion type" = "BREAK"
				"Fire from Attitude Adjuster explosion" = false
				#Range: 0 ~ 500
				"Attitude Adjuster explosion size" = 4

			[Functionality."Tools/Weapons".Explosions."Thunder Staff"]
				#NONE - The Thunder Staff will not affect the terrain.
				#BREAK - The Thunder Staff will drop some blocks that it breaks. (May not work due to lightning)
				#DESTROY - The Thunder Staff will destroy blocks and never drop them.
				#Allowed Values: NONE, BREAK, DESTROY
				"Thunder Staff explosion type" = "DESTROY"
				"Fire from Thunder Staff explosion" = true
				#Range: 0 ~ 500
				"Thunder Staff explosion size" = 4

		[Functionality."Tools/Weapons".Pickaxes]

			[Functionality."Tools/Weapons".Pickaxes."Ultimate Pickaxe"]
				"Enable Ultimate Pickaxe Tool Bonus (Fortune on Autosmelt)" = true

	[Functionality.Entity]

		[Functionality.Entity.Breeding]
			#Will Enchanted Animals be Breedable?
			"Enchanted Animal Breeding" = false

		[Functionality.Entity."Specific Entities"]

			[Functionality.Entity."Specific Entities"."Robo Warrior"]
				#NONE - The Robo Warrior will not affect the terrain.
				#BREAK - The Robo Warrior will drop some blocks that it breaks.
				#DESTROY - The Robo Warrior will destroy blocks and never drop them.
				#Allowed Values: NONE, BREAK, DESTROY
				"Ray Gun explosion type" = "BREAK"
				"Fire from Robo Warrior explosion" = false
				#Range: 0 ~ 500
				"Robo Warrior explosion size" = 6

			[Functionality.Entity."Specific Entities"."Wandering Trader"]
				#Can the Wandering Trader sell Uranium and Titanium?
				"Uranium and Titanium from Wandering Trader?" = false
				#Can the Wandering Trader sell Triffid Goo?
				"Triffid Goo from Wandering Trader?" = true

			[Functionality.Entity."Specific Entities"."Ender Dragon"]
				#Will the Ender Dragon Egg respawn after the first death?
				"Ender Dragon Egg Respawn" = true
				#Will the Ender Dragon drop her head?
				"Ender Dragon Head Drop" = true

	[Functionality.Armor]

		[Functionality.Armor."Emerald Armor"]
			"Enable the Emerald set bonus" = true
			#The multiplier by which villagers will discount their prices when a player is wearing a full emerald set. 
			# This multiplier stacks per each player in the area. Formula: 1 = 12.5% Discount, 2 = 25% Discount, etc.
			#Range: 0.0 ~ 8.0
			"Emerald Armor Set Discount Multiplier" = 4.0

		[Functionality.Armor."Lapis Armor"]
			"Enable the Lapis set bonus" = true
			#The power of each bookshelf around the enchantment table when a player with the full Lapis Armor Set is present. This effect stacks with each present player.
			#Range: 0 ~ 15
			"Lapis Armor Set Bookshelf Power Modifier" = 2

		[Functionality.Armor."Ender Dragon Scale Armor"]
			"Enable the Dragon Wings set bonus" = true
			#How the elytra on the Ender Dragon Scale Armor will get damaged,
			#where ARMOR means per hit, and ELYTRA means that it'll get damage every 20 ticks or so as you fly (basically the same as a normal elytra). 
			#This has yet to be functional in a future update
			#Allowed Values: ARMOR, ELYTRA
			"Ender Dragon Scale Armor elytra damage type" = "ELYTRA"

		[Functionality.Armor."Experience Armor"]
			#The multiplier for XP dropped, either by killing mobs or by breaking blocks. This doesn't work on randomly spawning XP orbs from 
			# the armor itself. Note that when killing a mob with the Experience Sword alongside the armor, the Experience Sword's multiplier 
			# will be added onto the armor's multiplier.
			#Range: 0 ~ 10000
			"Experience Armor Set XP Multiplier" = 3
			#The number you input here will affect how frequently XP orbs randomly spawn on you, should you be wearing the full Experience Armor set. 
			# The larger the number, the less frequent XP orbs will spawn on you.
			#Range: 0 ~ 100000
			"The max amount of time (in ticks) between each XP orb spawn" = 5500
			"Enable the Experience set bonus" = true

		[Functionality.Armor."Lava Eel Armor"]
			"Enable the Lava Eel set bonus" = true

	[Functionality."Update Checker"]
		#Send messages when there is a new update?
		"Show Update Messages" = true

	[Functionality.Spawners]
		#NO_BLOCKING - All Spawn Eggs can be used on a Spawner in Survival.
		#BLOCK_ALL - All Spawn Eggs will be blocked from being used on a Spawner in Survival.
		#BLOCK_CHAOS_AWAKENS - Only Spawn Eggs from Chaos Awakens will be blocked from being used on a Spawner in Survival.TAG_BLACKLISTED - Only Spawn Eggs which aren't tagged with the 'SPAWNER_SPAWN_EGG' tag can be used on a Spawner in Survival.TAG_WHITELISTED - Only Spawn Eggs which are tagged with the 'SPAWNER_SPAWN_EGG' tag can be used on a Spawner in Survival.
		#Allowed Values: NO_BLOCKING, BLOCK_ALL, BLOCK_CHAOS_AWAKENS, TAG_BLACKLISTED, TAG_WHITELISTED
		"Spawn Eggs on Spawners in Survival?" = "BLOCK_ALL"

	[Functionality.Textures]
		#Will holiday special textures be obtainable?
		"Obtainable Holiday Textures" = true

["World Generation"]
	"Enable fossil generation" = true
	"Enable ore generation" = true
	"Enable limestone generation in the mining dimension" = true
	"Enable infested ore generation" = true
	"Enable limestone generation in the overworld" = false
	#Will Nests spawn in the Overworld or the Ant Dimensions?
	"Ant Nest generation" = true
	"Enable rhinestone generation in the mining dimension" = true
	"Enable DZ ore generation" = true
	"Enable rhinestone generation in the overworld" = false
	"Enable marble generation in the overworld" = false
	#Will DZ ores spawn in the Overworld?
	"Overworld DZ Ores" = false
	"Enable marble generation in the mining dimension" = true

	["World Generation".Dimensions]

		["World Generation".Dimensions."Mining Paradise"]

			["World Generation".Dimensions."Mining Paradise".Biomes]

				["World Generation".Dimensions."Mining Paradise".Biomes."Stalagmite Valley"]
					#Enable/Disable ores generating on the stalagmites in the Stalagmite Valley.
					"Enable Stalagmite Ore Gen" = true

	["World Generation"."Specific Ore Spawning"]
		"Titanium ore generation" = true
		"Uranium ore generation" = true
		"Sunstone ore generation" = true
		"Bloodstone ore generation" = true
		"Silver ore generation" = true
		"Aluminum ore generation" = true
		"Tin ore generation" = true
		"Ruby ore generation" = true
		"Tiger's Eye ore generation" = true
		"Platinum ore generation" = true
		"Amethyst ore generation" = true
		"Salt ore generation" = true
		"Copper ore generation" = true

	["World Generation".Structures]
		#Will Wasp Nests be generated?
		"Generate Wasp Nests" = true
		#Will Jungle Ent Trees be generated?
		"Generate Jungle Ent Trees" = true
		#Will Acacia Ent Trees be generated?
		"Generate Acacia Ent Trees" = true
		#Will Dark Oak Ent Trees be generated?
		"Generate Dark Oak Ent Trees" = true
		#Will Crimson Ent Trees be generated?
		"Generate Crimson Ent Trees" = true
		#Will Birch Ent Trees be generated?
		"Generate Birch Ent Trees" = true
		#Will Oak Ent Trees be generated?
		"Generate Oak Ent Trees" = true
		#Will Warped Ent Trees be generated?
		"Generate Warped Ent Trees" = true
		#Will Spruce Ent Trees be generated?
		"Generate Spruce Ent Trees" = true
		#Will Ginkgo Ent Trees be generated?
		"Generate Ginkgo Ent Trees" = true
		#Will Jeffery Dungeons (Placeholders) be generated?
		"Generate Jeffery Dungeons" = true

[Dimensions]
	#Will the Butterfly teleport you to its Dimension?
	"Butterfly Teleport" = true
	#Will the Brown Ant teleport you to its Dimension?
	"Brown Ant Teleport" = true
	#Will the Rainbow Ant teleport you to its Dimension?
	"Rainbow Ant Teleport" = true
	#Will the Red Ant teleport you to its Dimension?
	"Red Ant Teleport" = true
	#Will the Unstable Ant teleport you to its Dimension?
	"Unstable Ant Teleport" = true
	#Will the Termite teleport you to its Dimension?
	"Termite Teleport" = true
	#Disable the requirement of needing an empty inventory to enter the Crystal World (Termite Dimension)?
	"Crystal World Requires Empty Inventory" = true

