
[ToolTips]
	"Enable tooltips" = true
	#(ToolTip color applies to both default tooltip description text and when shift-clicking).
	#Allowed Values: BLACK, DARK_BLUE, DARK_GREEN, DARK_AQUA, DARK_RED, DARK_PURPLE, GOLD, GRAY, DARK_GRAY, BLUE, GREEN, AQUA, RED, LIGHT_PURPLE, YELLOW, WHITE, OBFUSCATED, BOLD, STRIKETHROUGH, UNDERLINE, ITALIC, RESET
	"ToolTip Color" = "AQUA"
	"Enable damage tooltips" = true

	[ToolTips."Critter Cage"]
		"Display mob info on a filled critter cage" = true
		"Display the entity's registry name, alongside its modid" = true
		"Display the entity's display name" = true
		"Display the entity's health" = true
		"Display the villager's profession" = true
		"Display the villager's trading level" = true
		"Display the tamed entity's owner's name" = true
		"Display the tamed entity's collar color" = true

[Dimensions]

	[Dimensions."Crystal Dimension"]
		"Enable fog in the Crystal Dimension" = true
		"Enable particles in the Crystal Dimension" = true
		#Range: 0.0 ~ 1.0
		"Crystal Dimension fog density" = 0.03
		#Range: 0 ~ 100
		"Crystal Dimension particle density" = 2

[Functionality]

	[Functionality."VFX Effects"]
		#Enable/Disable all VFX effects under the 'VFX Effects' section.
		"Enable VFX effects" = true

		[Functionality."VFX Effects".Camera]
			"Enable camera shake" = true
			"Enable camera zoom" = true

	[Functionality.Armor]

		[Functionality.Armor."Lava Eel Armor"]
			#A static fog value for when you have the full Lava Eel set equipped and you're inside lava.
			#Range: 0.0 ~ 1.0
			"Lava fog density" = 0.019999999552965164
			#The position of fire on your screen when you're inside lava. 0 is the default. Positive moves it up, and negative moves it down.
			#Range: -1.0 ~ 1.0
			"Fire (y) Position on screen" = -0.5

