#
# How long before giving up should locate command, explorer maps, and other locating stuff
# do when locating a Integrated Dungeons and Structures's structure. This is in seconds.
#Range: 1.0 ~ 1000000.0
locateMaxTime = 15.0

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Abandoned Houses.
# 1 for spawning in most chunks and 1001 for none.
[Abandonedhouse]
	#Range: 1 ~ 1001
	abandonedhouseAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Brick Houses.
# 1 for spawning in most chunks and 1001 for none.
[Brickhouse]
	#Range: 1 ~ 1001
	brickhouseAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Castles.
# 1 for spawning in most chunks and 1001 for none.
[Castles]
	#Range: 1 ~ 1001
	castleAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Wizard Towers.
# 1 for spawning in most chunks and 1001 for none.
[Enchantingtowers]
	#Range: 1 ~ 1001
	enchantingtowerAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Wizard Towers.
# 1 for spawning in most chunks and 1001 for none.
[Wizardtowers]
	#Range: 1 ~ 1001
	wizardtowerAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Labyrinths.
# 1 for spawning in most chunks and 1001 for none.
[Labyrinth]
	#Range: 1 ~ 1001
	labyrinthAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Pillager Fortresses.
# 1 for spawning in most chunks and 1001 for none.
[PillagerFortress]
	#Range: 1 ~ 1001
	pillagerfortressAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Ancient Mines.
# 1 for spawning in most chunks and 1001 for none.
[AncientMines]
	#Range: 1 ~ 1001
	ancientminesAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Tinkers Workshop.
# 1 for spawning in most chunks and 1001 for none.
[TinkersWorkshop]
	#Range: 1 ~ 1001
	tinkersworkshopAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Sunken Ships.
# 1 for spawning in most chunks and 1001 for none.
[SunkenShip]
	#Range: 1 ~ 1001
	sunkenshipAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Coral Sunken Ships.
# 1 for spawning in most chunks and 1001 for none.
[SunkenShipCoral]
	#Range: 1 ~ 1001
	sunkenshipcoralAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Jungle Ancient Statues.
# 1 for spawning in most chunks and 1001 for none.
[AncientStatueJungle]
	#Range: 1 ~ 1001
	ancientstatuejungleAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Plains Ancient Statues.
# 1 for spawning in most chunks and 1001 for none.
[AncientStatuePlains]
	#Range: 1 ~ 1001
	ancientstatueplainsAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Desert Ancient Statues.
# 1 for spawning in most chunks and 1001 for none.
[AncientStatueDesert]
	#Range: 1 ~ 1001
	ancientstatuedesertAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Desert Markets.
# 1 for spawning in most chunks and 1001 for none.
[DesertMarket]
	#Range: 1 ~ 1001
	desertmarketAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Red Desert Markets.
# 1 for spawning in most chunks and 1001 for none.
[RedDesertMarket]
	#Range: 1 ~ 1001
	desertmarketredAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Orange Desert Markets.
# 1 for spawning in most chunks and 1001 for none.
[OrangeDesertMarket]
	#Range: 1 ~ 1001
	desertmarketorangeAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Desert Camps.
# 1 for spawning in most chunks and 1001 for none.
[DesertCamp]
	#Range: 1 ~ 1001
	desertcampAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Red Desert Camps.
# 1 for spawning in most chunks and 1001 for none.
[RedDesertCamp]
	#Range: 1 ~ 1001
	desertcampredAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Orange Desert Camps.
# 1 for spawning in most chunks and 1001 for none.
[OrangeDesertCamp]
	#Range: 1 ~ 1001
	desertcamporangeAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Pillager Camps.
# 1 for spawning in most chunks and 1001 for none.
[PillagerCamp]
	#Range: 1 ~ 1001
	pillagercampAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Washing Camps.
# 1 for spawning in most chunks and 1001 for none.
[WashingCamp]
	#Range: 1 ~ 1001
	washingcampAverageChunkDistance = 100

#-----------------------------------------------------------------------------------------
# Average distance between spawn attempts for IDAS Polar Bear Dens.
# 1 for spawning in most chunks and 1001 for none.
[PolarBearDen]

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Hermit's Hollows
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.HermitsHollow]
		#Range: 1 ~ 1001
		hermitshollowAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS BYG Mahogany Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BYGMahoganyLumberCamp]
		#Range: 1 ~ 1001
		lumbercampbygmahoganyAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Apothecary Abodes
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.ApothecaryAbode]
		#Range: 1 ~ 1001
		apothecaryabodeAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Forest (Wolf/Bear) Dens.
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.PolarBearDen]
		#Range: 1 ~ 1001
		polarbeardenAverageChunkDistance = 100
		#Range: 1 ~ 1001
		forestdenAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS BOP Mahogany Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BOPMahoganyLumberCamp]
		#Range: 1 ~ 1001
		lumbercampbopmahoganyAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Birch Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BirchLumberCamp]
		#Range: 1 ~ 1001
		lumbercampbirchAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS BYG Redwood Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BYGRedwoodLumberCamp]
		#Range: 1 ~ 1001
		lumbercampbygredwoodAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Oak Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.OakLumberCamp]
		#Range: 1 ~ 1001
		lumbercampoakAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Treetop Taverns
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen."Treetop Taverns"]
		#Range: 1 ~ 1001
		treetoptavernAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS BOP Redwood Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BOPRedwoodLumberCamp]
		#Range: 1 ~ 1001
		lumbercampbopredwoodAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Beekeepers House
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BeekeepersHouse]
		#Range: 1 ~ 1001
		beekeepershouseAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Jungle Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.JungleLumberCamp]
		#Range: 1 ~ 1001
		lumbercampjungleAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Bearclaw Inns
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.BearclawInn]
		#Range: 1 ~ 1001
		bearclawinnAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Dread Citadels
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen."Dread Citadels"]
		#Range: 1 ~ 1001
		dreadcitadelAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Hunters Cabin
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.HuntersCabin]
		#Range: 1 ~ 1001
		hunterscabinAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Farmhouses
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.Farmhouse]
		#Range: 1 ~ 1001
		farmhouseAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Dark Oak Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.DarkOakLumberCamp]
		#Range: 1 ~ 1001
		lumbercampdarkoakAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Witches Treestumps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.WitchesTreestump]
		#Range: 1 ~ 1001
		witchestreestumpAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Bazaars
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.Bazaar]
		#Range: 1 ~ 1001
		bazaarAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Redhorn Guilds
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.RehornGuild]
		#Range: 1 ~ 1001
		redhornguildAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Deep Underground Camps.
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.UndergroundCamp]
		#Range: 1 ~ 1001
		undergroundcampdeepAverageChunkDistance = 100
		#Range: 1 ~ 1001
		undergroundcampAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Acacia Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.AcaciaLumberCamp]
		#Range: 1 ~ 1001
		lumbercampacaciaAverageChunkDistance = 100

	#-----------------------------------------------------------------------------------------
	# Average distance between spawn attempts for IDAS Spruce Lumber Camps
	# 1 for spawning in most chunks and 1001 for none.
	[PolarBearDen.SpruceLumberCamp]
		#Range: 1 ~ 1001
		lumbercampspruceAverageChunkDistance = 100

